const SOCKET_EVENTS = {
    DIRECT_MESSAGE: "DIRECT_MESSAGE",
    ADD_FRIEND: "ADD_FRIEND",
    USER_DISCONNECTING: "USER_DISCONNECTING",
    USER_CONNECTED: "USER_CONNECTED",
    GET_FRIENDLIST: "GET_FRIENDLIST",
    GET_MESSAGES: "GET_MESSAGES"
}

module.exports = SOCKET_EVENTS